"use client";

import { useId, useState } from "react";
import Button from "@/components/Button";
import Input from "@/components/Input";
import {
  YOUTUBE_OUTPUT_MODES,
  countWords,
  describeTranscriptResult,
  downloadTranscriptSrt,
  downloadTranscriptTxt,
  formatTranscriptOutput,
  validateYoutubeUrl,
  youtubeWatchUrl,
  type YoutubeOutputMode,
  type YoutubeTranscriptResult,
  type YoutubeTranscriptSegment,
} from "@/lib/youtube-to-text";
import { cn, copyText } from "@/lib/utils";

type ApiSuccess = {
  videoId: string;
  title: string;
  language: string;
  languageCode: string;
  isAutoGenerated: boolean;
  mode: YoutubeOutputMode;
  text: string;
  segments: YoutubeTranscriptSegment[];
  error?: string;
};

const EXAMPLE_URLS = [
  {
    label: "TED talk",
    url: "https://www.youtube.com/watch?v=arj7oStGLkU",
  },
  {
    label: "Short sample",
    url: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
  },
];

export default function YoutubeToText() {
  const urlId = useId();
  const modeId = useId();
  const outputId = useId();

  const [url, setUrl] = useState("");
  const [mode, setMode] = useState<YoutubeOutputMode>("plain");
  const [result, setResult] = useState<YoutubeTranscriptResult | null>(null);
  const [text, setText] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const hasResult = result !== null;
  const wordCount = countWords(text);
  const canExtract = url.trim().length > 0 && !loading;

  async function extractTranscript(nextMode = mode) {
    const urlError = validateYoutubeUrl(url);
    if (urlError) {
      setError(urlError);
      return;
    }

    setLoading(true);
    setError("");
    setCopied(false);

    try {
      const response = await fetch("/api/youtube-to-text", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          url: url.trim(),
          language: "auto",
          mode: nextMode,
        }),
      });

      const data = (await response.json().catch(() => null)) as
        | ApiSuccess
        | { error?: string }
        | null;

      if (!response.ok) {
        throw new Error(
          data && "error" in data && data.error
            ? data.error
            : "Could not extract text from this YouTube video.",
        );
      }

      if (!data || !("segments" in data) || !data.segments?.length) {
        throw new Error("Could not extract text from this YouTube video.");
      }

      const nextResult: YoutubeTranscriptResult = {
        videoId: data.videoId,
        title: data.title,
        language: data.language,
        languageCode: data.languageCode,
        isAutoGenerated: data.isAutoGenerated,
        text: data.text,
        segments: data.segments,
      };

      setResult(nextResult);
      setText(formatTranscriptOutput(nextResult, nextMode));
      setMode(nextMode);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Could not extract text from this YouTube video.",
      );
    } finally {
      setLoading(false);
    }
  }

  function handleModeChange(nextMode: YoutubeOutputMode) {
    setMode(nextMode);
    if (!result) return;
    setText(formatTranscriptOutput(result, nextMode));
    setCopied(false);
  }

  function handleReset() {
    setUrl("");
    setResult(null);
    setText("");
    setError("");
    setCopied(false);
    setMode("plain");
  }

  async function handleCopy() {
    if (!text.trim()) return;
    const ok = await copyText(text);
    if (ok) {
      setCopied(true);
      setError("");
      setTimeout(() => setCopied(false), 1600);
      return;
    }
    setError("Could not copy to clipboard. Try selecting the text manually.");
  }

  function handleDownloadTxt() {
    if (!result || !text.trim()) return;
    downloadTranscriptTxt(text, result.videoId, mode);
    setError("");
  }

  function handleDownloadSrt() {
    if (!result?.segments.length) return;
    downloadTranscriptSrt(result.segments, result.videoId);
    setError("");
  }

  return (
    <div className="tool-grid youtube-to-text">
      <div className="tool-panel">
        <Input
          id={urlId}
          label="YouTube URL"
          value={url}
          onChange={(event) => {
            setUrl(event.target.value);
            if (error) setError("");
          }}
          placeholder="https://www.youtube.com/watch?v=…"
          hint="Paste a watch, youtu.be, Shorts, or Live link — or an 11-character video ID"
          inputMode="url"
          autoComplete="off"
          spellCheck={false}
          disabled={loading}
        />

        <div className="youtube-to-text__examples" aria-label="Example videos">
          {EXAMPLE_URLS.map((example) => (
            <button
              key={example.url}
              type="button"
              className="youtube-to-text__example"
              disabled={loading}
              onClick={() => {
                setUrl(example.url);
                if (error) setError("");
              }}
            >
              Try {example.label}
            </button>
          ))}
        </div>

        <div className="youtube-to-text__options">
          <div className="ui-field">
            <span className="ui-label" id={modeId}>
              Output format
            </span>
            <div
              className="youtube-to-text__chips"
              role="radiogroup"
              aria-labelledby={modeId}
            >
              {YOUTUBE_OUTPUT_MODES.map((option) => {
                const selected = mode === option.id;
                return (
                  <button
                    key={option.id}
                    type="button"
                    role="radio"
                    aria-checked={selected}
                    className={cn(
                      "youtube-to-text__chip",
                      selected && "is-active",
                    )}
                    disabled={loading}
                    onClick={() => handleModeChange(option.id)}
                  >
                    <span className="youtube-to-text__chip-label">
                      {option.label}
                    </span>
                    <span className="youtube-to-text__chip-hint">
                      {option.hint}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        <div className="tool-actions">
          <Button
            onClick={() => void extractTranscript(mode)}
            disabled={!canExtract}
          >
            {loading ? "Extracting…" : "Extract text"}
          </Button>
          <Button
            variant="ghost"
            onClick={handleReset}
            disabled={loading || (!url && !hasResult)}
          >
            Start over
          </Button>
        </div>

        {hasResult && text.trim() ? (
          <div className="tool-actions">
            <Button onClick={() => void handleCopy()}>
              {copied ? "Copied" : "Copy text"}
            </Button>
            <Button variant="ghost" onClick={handleDownloadTxt}>
              Download .txt
            </Button>
            <Button variant="ghost" onClick={handleDownloadSrt}>
              Download .srt
            </Button>
          </div>
        ) : null}

        {error ? (
          <p className="tool-error" role="alert">
            {error}
          </p>
        ) : null}
      </div>

      <div className="tool-panel tool-panel--preview">
        <div
          className={cn(
            "tool-stage youtube-to-text__stage",
            hasResult && "is-ready",
            loading && "is-loading",
          )}
        >
          {loading ? (
            <div className="tool-loading" role="status" aria-live="polite">
              <span className="tool-loading__spinner" aria-hidden="true" />
              <span className="tool-loading__text">
                Fetching YouTube captions…
              </span>
              <span className="tool-loading__subtext">
                Pulls official or auto-generated subtitles when available.
              </span>
            </div>
          ) : hasResult ? (
            <div className="youtube-to-text__result">
              <div className="youtube-to-text__meta">
                <p className="youtube-to-text__title">{result.title}</p>
                <p className="youtube-to-text__result-meta">
                  {describeTranscriptResult(result, text)}
                </p>
                <a
                  className="youtube-to-text__link"
                  href={youtubeWatchUrl(result.videoId)}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Open on YouTube
                </a>
              </div>
              <label className="ui-label" htmlFor={outputId}>
                Transcript
              </label>
              <textarea
                id={outputId}
                className="ui-input ui-input--textarea youtube-to-text__textarea"
                value={text}
                onChange={(event) => {
                  setText(event.target.value);
                  setCopied(false);
                }}
                rows={16}
                spellCheck
                placeholder="Transcript text will appear here"
              />
            </div>
          ) : (
            <p className="tool-placeholder">
              Paste a YouTube link to extract the transcript here
            </p>
          )}
        </div>
        <p className="tool-hint">
          {hasResult
            ? `${wordCount.toLocaleString()} words · edit, copy, or download TXT/SRT`
            : "YouTube to text · uses video captions · free, no account"}
        </p>
      </div>
    </div>
  );
}
