"use client";

import { useId, useState } from "react";
import Button from "@/components/Button";
import Input from "@/components/Input";
import {
  YOUTUBE_SUMMARY_STYLES,
  describeSummaryResult,
  downloadYoutubeSummaryTxt,
  validateYoutubeUrl,
  type YoutubeSummaryStyleId,
} from "@/lib/youtube-summarize";
import { youtubeWatchUrl } from "@/lib/youtube-to-text";
import { cn, copyText } from "@/lib/utils";

type ApiSuccess = {
  videoId: string;
  title: string;
  language: string;
  languageCode: string;
  isAutoGenerated: boolean;
  source?: "captions" | "speech";
  style: YoutubeSummaryStyleId;
  truncated: boolean;
  summary: string;
  error?: string;
};

type SummaryMeta = {
  videoId: string;
  title: string;
  source: "captions" | "speech";
  truncated: boolean;
};

const EXAMPLE_URLS = [
  {
    label: "TED talk",
    url: "https://www.youtube.com/watch?v=arj7oStGLkU",
  },
  {
    label: "Short sample",
    url: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
  },
];

export default function YoutubeSummarize() {
  const urlId = useId();
  const styleId = useId();
  const outputId = useId();

  const [url, setUrl] = useState("");
  const [style, setStyle] = useState<YoutubeSummaryStyleId>("brief");
  const [meta, setMeta] = useState<SummaryMeta | null>(null);
  const [summary, setSummary] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const hasResult = meta !== null && summary.trim().length > 0;
  const canSummarize = url.trim().length > 0 && !loading;

  async function summarizeVideo(nextStyle = style) {
    const urlError = validateYoutubeUrl(url);
    if (urlError) {
      setError(urlError);
      return;
    }

    setLoading(true);
    setError("");
    setCopied(false);

    try {
      const response = await fetch("/api/youtube-summarize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          url: url.trim(),
          language: "auto",
          style: nextStyle,
        }),
      });

      const data = (await response.json().catch(() => null)) as
        | ApiSuccess
        | { error?: string }
        | null;

      if (!response.ok) {
        throw new Error(
          data && "error" in data && data.error
            ? data.error
            : "Could not summarize this YouTube video.",
        );
      }

      if (!data || !("summary" in data) || !data.summary?.trim()) {
        throw new Error("Could not summarize this YouTube video.");
      }

      setMeta({
        videoId: data.videoId,
        title: data.title,
        source: data.source === "speech" ? "speech" : "captions",
        truncated: Boolean(data.truncated),
      });
      setSummary(data.summary.trim());
      setStyle(nextStyle);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Could not summarize this YouTube video.",
      );
    } finally {
      setLoading(false);
    }
  }

  function handleReset() {
    setUrl("");
    setMeta(null);
    setSummary("");
    setError("");
    setCopied(false);
    setStyle("brief");
  }

  async function handleCopy() {
    if (!summary.trim()) return;
    const ok = await copyText(summary);
    if (ok) {
      setCopied(true);
      setError("");
      setTimeout(() => setCopied(false), 1600);
      return;
    }
    setError("Could not copy to clipboard. Try selecting the text manually.");
  }

  function handleDownload() {
    if (!meta || !summary.trim()) return;
    downloadYoutubeSummaryTxt(summary, meta.videoId, style);
    setError("");
  }

  return (
    <div className="tool-grid youtube-summarize">
      <div className="tool-panel">
        <Input
          id={urlId}
          label="YouTube URL"
          value={url}
          onChange={(event) => {
            setUrl(event.target.value);
            if (error) setError("");
          }}
          placeholder="https://www.youtube.com/watch?v=…"
          hint="Paste a watch, youtu.be, Shorts, or Live link — or an 11-character video ID"
          inputMode="url"
          autoComplete="off"
          spellCheck={false}
          disabled={loading}
        />

        <div className="youtube-summarize__examples" aria-label="Example videos">
          {EXAMPLE_URLS.map((example) => (
            <button
              key={example.url}
              type="button"
              className="youtube-summarize__example"
              disabled={loading}
              onClick={() => {
                setUrl(example.url);
                if (error) setError("");
              }}
            >
              Try {example.label}
            </button>
          ))}
        </div>

        <div className="youtube-summarize__options">
          <div className="ui-field">
            <span className="ui-label" id={styleId}>
              Summary style
            </span>
            <div
              className="youtube-summarize__chips"
              role="radiogroup"
              aria-labelledby={styleId}
            >
              {YOUTUBE_SUMMARY_STYLES.map((option) => {
                const selected = style === option.id;
                return (
                  <button
                    key={option.id}
                    type="button"
                    role="radio"
                    aria-checked={selected}
                    className={cn(
                      "youtube-summarize__chip",
                      selected && "is-active",
                    )}
                    disabled={loading}
                    onClick={() => setStyle(option.id)}
                  >
                    <span className="youtube-summarize__chip-label">
                      {option.label}
                    </span>
                    <span className="youtube-summarize__chip-hint">
                      {option.hint}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        <div className="tool-actions">
          <Button
            onClick={() => void summarizeVideo(style)}
            disabled={!canSummarize}
          >
            {loading ? "Summarizing…" : "Summarize"}
          </Button>
          <Button
            variant="ghost"
            onClick={handleReset}
            disabled={loading || (!url && !hasResult)}
          >
            Start over
          </Button>
        </div>

        {hasResult ? (
          <div className="tool-actions">
            <Button onClick={() => void handleCopy()}>
              {copied ? "Copied" : "Copy summary"}
            </Button>
            <Button variant="ghost" onClick={handleDownload}>
              Download .txt
            </Button>
          </div>
        ) : null}

        {error ? (
          <p className="tool-error" role="alert">
            {error}
          </p>
        ) : null}
      </div>

      <div className="tool-panel tool-panel--preview">
        <div
          className={cn(
            "tool-stage youtube-summarize__stage",
            hasResult && "is-ready",
            loading && "is-loading",
          )}
        >
          {loading ? (
            <div className="tool-loading" role="status" aria-live="polite">
              <span className="tool-loading__spinner" aria-hidden="true" />
              <span className="tool-loading__text">
                Summarizing YouTube video…
              </span>
              <span className="tool-loading__subtext">
                Pulls captions when available, otherwise transcribes speech,
                then writes a summary.
              </span>
            </div>
          ) : hasResult && meta ? (
            <div className="youtube-summarize__result">
              <div className="youtube-summarize__meta">
                <p className="youtube-summarize__title">{meta.title}</p>
                <p className="youtube-summarize__result-meta">
                  {describeSummaryResult({
                    styleId: style,
                    summary,
                    source: meta.source,
                    truncated: meta.truncated,
                  })}
                </p>
                <a
                  className="youtube-summarize__link"
                  href={youtubeWatchUrl(meta.videoId)}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Open on YouTube
                </a>
              </div>
              <label className="ui-label" htmlFor={outputId}>
                Summary
              </label>
              <textarea
                id={outputId}
                className="ui-input ui-input--textarea youtube-summarize__textarea"
                value={summary}
                onChange={(event) => {
                  setSummary(event.target.value);
                  setCopied(false);
                }}
                rows={16}
                spellCheck
                placeholder="Summary text will appear here"
              />
            </div>
          ) : (
            <p className="tool-placeholder">
              Paste a YouTube link to generate a summary here
            </p>
          )}
        </div>
        <p className="tool-hint">
          {hasResult
            ? "Edit, copy, or download the summary as TXT"
            : "Summarize YouTube · brief, detailed, or key points · free, no account"}
        </p>
      </div>
    </div>
  );
}
