import { downloadBlob } from "@/lib/image";

const VIDEO_ID_RE = /^[\w-]{11}$/;

export type YoutubeTranscriptSegment = {
  start: number;
  duration: number;
  text: string;
};

export type YoutubeTranscriptSource = "captions" | "speech";

export type YoutubeTranscriptResult = {
  videoId: string;
  title: string;
  language: string;
  languageCode: string;
  isAutoGenerated: boolean;
  /** captions = YouTube CC track; speech = Whisper from audio */
  source?: YoutubeTranscriptSource;
  text: string;
  segments: YoutubeTranscriptSegment[];
};

export type YoutubeOutputMode = "plain" | "timestamped";

export const YOUTUBE_OUTPUT_MODES: Array<{
  id: YoutubeOutputMode;
  label: string;
  hint: string;
}> = [
  { id: "plain", label: "Plain text", hint: "Readable paragraphs" },
  { id: "timestamped", label: "With timestamps", hint: "[mm:ss] lines" },
];

export function isYoutubeOutputMode(value: unknown): value is YoutubeOutputMode {
  return value === "plain" || value === "timestamped";
}

export function parseYoutubeVideoId(input: string): string | null {
  const trimmed = input.trim();
  if (!trimmed) return null;
  if (VIDEO_ID_RE.test(trimmed)) return trimmed;

  const withProtocol = /^https?:\/\//i.test(trimmed)
    ? trimmed
    : `https://${trimmed}`;

  try {
    const url = new URL(withProtocol);
    const host = url.hostname.replace(/^www\./i, "").toLowerCase();

    if (host === "youtu.be") {
      const id = url.pathname.split("/").filter(Boolean)[0] ?? "";
      return VIDEO_ID_RE.test(id) ? id : null;
    }

    if (
      host === "youtube.com" ||
      host === "m.youtube.com" ||
      host === "music.youtube.com" ||
      host === "youtube-nocookie.com"
    ) {
      const fromQuery = url.searchParams.get("v");
      if (fromQuery && VIDEO_ID_RE.test(fromQuery)) return fromQuery;

      const match = url.pathname.match(
        /^\/(?:embed|shorts|live|v)\/([\w-]{11})/,
      );
      if (match?.[1]) return match[1];
    }
  } catch {
    return null;
  }

  return null;
}

export function validateYoutubeUrl(input: string): string | null {
  const trimmed = input.trim();
  if (!trimmed) return "Paste a YouTube URL or video ID.";
  if (!parseYoutubeVideoId(trimmed)) {
    return "Enter a valid YouTube URL (watch, youtu.be, shorts, or live) or 11-character video ID.";
  }
  return null;
}

export function formatTimestamp(seconds: number): string {
  const safe = Math.max(0, Math.floor(seconds));
  const hours = Math.floor(safe / 3600);
  const minutes = Math.floor((safe % 3600) / 60);
  const secs = safe % 60;
  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, "0")}:${String(secs).padStart(2, "0")}`;
  }
  return `${minutes}:${String(secs).padStart(2, "0")}`;
}

export function segmentsToPlainText(
  segments: YoutubeTranscriptSegment[],
): string {
  const chunks: string[] = [];
  let buffer = "";

  for (const segment of segments) {
    const piece = segment.text.trim();
    if (!piece) continue;
    if (!buffer) {
      buffer = piece;
      continue;
    }
    const needsSpace = !buffer.endsWith("\n") && !piece.startsWith("\n");
    buffer += needsSpace ? ` ${piece}` : piece;
    if (/[.!?…]["')\]]*$/.test(piece) || buffer.length > 420) {
      chunks.push(buffer.trim());
      buffer = "";
    }
  }

  if (buffer.trim()) chunks.push(buffer.trim());
  return chunks.join("\n\n");
}

export function segmentsToTimestampedText(
  segments: YoutubeTranscriptSegment[],
): string {
  return segments
    .map((segment) => {
      const text = segment.text.trim();
      if (!text) return "";
      return `[${formatTimestamp(segment.start)}] ${text}`;
    })
    .filter(Boolean)
    .join("\n");
}

export function formatTranscriptOutput(
  result: Pick<YoutubeTranscriptResult, "segments" | "text">,
  mode: YoutubeOutputMode,
): string {
  if (mode === "timestamped") {
    return segmentsToTimestampedText(result.segments) || result.text;
  }
  return segmentsToPlainText(result.segments) || result.text;
}

export function segmentsToSrt(segments: YoutubeTranscriptSegment[]): string {
  const blocks: string[] = [];
  let index = 1;

  for (const segment of segments) {
    const text = segment.text.trim();
    if (!text) continue;
    const start = Math.max(0, segment.start);
    const end = Math.max(start + 0.2, start + Math.max(segment.duration, 0.2));
    blocks.push(
      `${index}\n${toSrtTime(start)} --> ${toSrtTime(end)}\n${text}\n`,
    );
    index += 1;
  }

  return blocks.join("\n");
}

function toSrtTime(seconds: number): string {
  const totalMs = Math.round(Math.max(0, seconds) * 1000);
  const hours = Math.floor(totalMs / 3_600_000);
  const minutes = Math.floor((totalMs % 3_600_000) / 60_000);
  const secs = Math.floor((totalMs % 60_000) / 1000);
  const ms = totalMs % 1000;
  return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(secs).padStart(2, "0")},${String(ms).padStart(3, "0")}`;
}

export function countWords(text: string): number {
  const trimmed = text.trim();
  if (!trimmed) return 0;
  return trimmed.split(/\s+/).length;
}

export function describeTranscriptResult(
  result: YoutubeTranscriptResult,
  outputText: string,
): string {
  const words = countWords(outputText);
  const source =
    result.source === "speech"
      ? "speech transcription"
      : result.isAutoGenerated
        ? "auto captions"
        : "manual captions";
  const lang = result.language || result.languageCode || "unknown";
  return `${words.toLocaleString()} words · ${result.segments.length} segments · ${lang} · ${source}`;
}

export function downloadTranscriptTxt(
  text: string,
  videoId: string,
  mode: YoutubeOutputMode,
): void {
  const suffix = mode === "timestamped" ? "timestamps" : "transcript";
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  downloadBlob(blob, `youtube-${videoId}-${suffix}.txt`);
}

export function downloadTranscriptSrt(
  segments: YoutubeTranscriptSegment[],
  videoId: string,
): void {
  const blob = new Blob([segmentsToSrt(segments)], {
    type: "application/x-subrip;charset=utf-8",
  });
  downloadBlob(blob, `youtube-${videoId}.srt`);
}

export function youtubeWatchUrl(videoId: string): string {
  return `https://www.youtube.com/watch?v=${videoId}`;
}
