import { fetchYoutubeTranscript } from "@/lib/youtube-transcript-server";
import {
  formatTranscriptOutput,
  isYoutubeOutputMode,
  validateYoutubeUrl,
} from "@/lib/youtube-to-text";

export const runtime = "nodejs";
export const maxDuration = 60;

type RequestBody = {
  url?: unknown;
  language?: unknown;
  mode?: unknown;
};

function jsonError(message: string, status: number) {
  return Response.json({ error: message }, { status });
}

export async function POST(request: Request) {
  let body: RequestBody;
  try {
    body = (await request.json()) as RequestBody;
  } catch {
    return jsonError("Invalid JSON body.", 400);
  }

  const url = typeof body.url === "string" ? body.url : "";
  const urlError = validateYoutubeUrl(url);
  if (urlError) return jsonError(urlError, 400);

  const language =
    typeof body.language === "string" && body.language.trim()
      ? body.language.trim()
      : "auto";
  const mode = isYoutubeOutputMode(body.mode) ? body.mode : "plain";

  try {
    const result = await fetchYoutubeTranscript(url, { language });
    const text = formatTranscriptOutput(result, mode);

    return Response.json({
      videoId: result.videoId,
      title: result.title,
      language: result.language,
      languageCode: result.languageCode,
      isAutoGenerated: result.isAutoGenerated,
      mode,
      text,
      segments: result.segments,
    });
  } catch (err) {
    const message =
      err instanceof Error
        ? err.message
        : "Could not extract text from this YouTube video.";

    const status =
      /valid YouTube|Paste a YouTube/i.test(message)
        ? 400
        : /No captions|empty|unavailable/i.test(message)
          ? 422
          : 502;

    return jsonError(message, status);
  }
}
