import {
  GroqTranscribeError,
  transcribeAudioWithGroq,
} from "@/lib/groq-transcribe-server";
import { isTranscribeLanguageId } from "@/lib/video-transcribe-shared";
import { downloadYoutubeAudio } from "@/lib/youtube-audio-server";
import {
  formatTranscriptOutput,
  isYoutubeOutputMode,
  validateYoutubeUrl,
  type YoutubeTranscriptResult,
} from "@/lib/youtube-to-text";
import { fetchYoutubeTranscript } from "@/lib/youtube-transcript-server";
import { trackToolUsageServer } from "@/lib/analytics/track";
import { getToolBySlug } from "@/data/tools";
import { publicErrorMessage } from "@/lib/security/public-error";
import { guardApiRequest } from "@/lib/security/request";

export const runtime = "nodejs";
export const maxDuration = 60;

const TOOL_SLUG = "youtube-to-text";

type RequestBody = {
  url?: unknown;
  language?: unknown;
  mode?: unknown;
  /** Prefer captions, fall back to speech. Or force speech. */
  method?: unknown;
};

function jsonError(message: string, status: number) {
  return Response.json({ error: message }, { status });
}

function track(request: Request, success: boolean) {
  const tool = getToolBySlug(TOOL_SLUG);
  if (tool) {
    trackToolUsageServer(
      { toolId: tool.slug, toolName: tool.name, success },
      request,
    );
  }
}

function isNoCaptionsError(message: string): boolean {
  return /No captions|empty|Captions were empty/i.test(message);
}

async function transcribeFromSpeech(
  url: string,
  language: string,
): Promise<YoutubeTranscriptResult> {
  const audio = await downloadYoutubeAudio(url);
  const whisperLanguage = isTranscribeLanguageId(language)
    ? language
    : "auto";

  const transcript = await transcribeAudioWithGroq({
    bytes: audio.bytes,
    filename: audio.filename,
    mimeType: audio.mimeType,
    language: whisperLanguage,
    durationHint: audio.durationSec || undefined,
  });

  const segments = transcript.segments.map((segment) => ({
    start: segment.start,
    duration: Math.max(0.2, segment.end - segment.start),
    text: segment.text,
  }));

  return {
    videoId: audio.videoId,
    title: audio.title,
    language: whisperLanguage === "en" ? "English" : "auto",
    languageCode: whisperLanguage === "en" ? "en" : "auto",
    isAutoGenerated: true,
    source: "speech",
    text: transcript.text,
    segments:
      segments.length > 0
        ? segments
        : [
            {
              start: 0,
              duration: audio.durationSec || 1,
              text: transcript.text,
            },
          ],
  };
}

export async function POST(request: Request) {
  const guarded = guardApiRequest(request, {
    bucket: "youtube-to-text",
    limit: 15,
    windowMs: 60_000,
    requireSameOrigin: true,
    maxBodyBytes: 8_192,
  });
  if (guarded) return guarded;

  let body: RequestBody;
  try {
    body = (await request.json()) as RequestBody;
  } catch {
    return jsonError("Invalid JSON body.", 400);
  }

  const url = typeof body.url === "string" ? body.url : "";
  const urlError = validateYoutubeUrl(url);
  if (urlError) return jsonError(urlError, 400);

  const language =
    typeof body.language === "string" && body.language.trim()
      ? body.language.trim()
      : "auto";
  const mode = isYoutubeOutputMode(body.mode) ? body.mode : "plain";
  const method =
    body.method === "speech" || body.method === "captions"
      ? body.method
      : "auto";

  try {
    let result: YoutubeTranscriptResult;

    if (method === "speech") {
      result = await transcribeFromSpeech(url, language);
    } else if (method === "captions") {
      result = await fetchYoutubeTranscript(url, { language });
      result = { ...result, source: "captions" };
    } else {
      try {
        result = await fetchYoutubeTranscript(url, { language });
        result = { ...result, source: "captions" };
      } catch (captionErr) {
        const captionMessage =
          captionErr instanceof Error
            ? captionErr.message
            : "Could not extract captions.";
        if (!isNoCaptionsError(captionMessage)) {
          throw captionErr;
        }
        result = await transcribeFromSpeech(url, language);
      }
    }

    const text = formatTranscriptOutput(result, mode);

    track(request, true);

    return Response.json({
      videoId: result.videoId,
      title: result.title,
      language: result.language,
      languageCode: result.languageCode,
      isAutoGenerated: result.isAutoGenerated,
      source: result.source ?? "captions",
      mode,
      text,
      segments: result.segments,
    });
  } catch (err) {
    if (err instanceof GroqTranscribeError) {
      track(request, false);
      return jsonError(
        publicErrorMessage(err, "Could not process this request."),
        err.status,
      );
    }

    const message = publicErrorMessage(
      err,
      "Could not extract text from this YouTube video.",
    );

    const status =
      /valid YouTube|Paste a YouTube|up to \d+ minutes/i.test(message)
        ? 400
        : /No captions|empty|unavailable|restricted|region-locked|No speech/i.test(
              message,
            )
          ? 422
          : /temporarily unavailable|not configured/i.test(message)
            ? 503
            : 502;

    if (status !== 400) {
      track(request, false);
    }

    return jsonError(message, status);
  }
}
