import {
  GroqTranscribeError,
  transcribeAudioWithGroq,
} from "@/lib/groq-transcribe-server";
import { isTranscribeLanguageId } from "@/lib/video-transcribe-shared";
import { downloadYoutubeAudio } from "@/lib/youtube-audio-server";
import {
  buildYoutubeSummarySystemPrompt,
  buildYoutubeSummaryUserPrompt,
  isYoutubeSummaryStyleId,
  truncateTranscriptForSummary,
  validateYoutubeUrl,
  type YoutubeSummaryStyleId,
} from "@/lib/youtube-summarize";
import {
  formatTranscriptOutput,
  type YoutubeTranscriptResult,
} from "@/lib/youtube-to-text";
import { fetchYoutubeTranscript } from "@/lib/youtube-transcript-server";

export const runtime = "nodejs";
export const maxDuration = 60;

type RequestBody = {
  url?: unknown;
  style?: unknown;
  language?: unknown;
};

function jsonError(message: string, status: number) {
  return Response.json({ error: message }, { status });
}

function isNoCaptionsError(message: string): boolean {
  return /No captions|empty|Captions were empty/i.test(message);
}

function extractGeneratedText(payload: unknown): string | null {
  if (typeof payload === "string") {
    const trimmed = payload.trim();
    return trimmed || null;
  }

  if (!payload || typeof payload !== "object") return null;

  const record = payload as Record<string, unknown>;

  if (typeof record.summary === "string" && record.summary.trim()) {
    return record.summary.trim();
  }

  if (typeof record.text === "string" && record.text.trim()) {
    return record.text.trim();
  }

  const choices = record.choices;
  if (Array.isArray(choices) && choices[0] && typeof choices[0] === "object") {
    const choice = choices[0] as Record<string, unknown>;
    const message = choice.message;
    if (message && typeof message === "object") {
      const content = (message as Record<string, unknown>).content;
      if (typeof content === "string" && content.trim()) {
        return content.trim();
      }
    }
    if (typeof choice.text === "string" && choice.text.trim()) {
      return choice.text.trim();
    }
  }

  return null;
}

async function transcribeFromSpeech(
  url: string,
  language: string,
): Promise<YoutubeTranscriptResult> {
  const audio = await downloadYoutubeAudio(url);
  const whisperLanguage = isTranscribeLanguageId(language)
    ? language
    : "auto";

  const transcript = await transcribeAudioWithGroq({
    bytes: audio.bytes,
    filename: audio.filename,
    mimeType: audio.mimeType,
    language: whisperLanguage,
    durationHint: audio.durationSec || undefined,
  });

  const segments = transcript.segments.map((segment) => ({
    start: segment.start,
    duration: Math.max(0.2, segment.end - segment.start),
    text: segment.text,
  }));

  return {
    videoId: audio.videoId,
    title: audio.title,
    language: whisperLanguage === "en" ? "English" : "auto",
    languageCode: whisperLanguage === "en" ? "en" : "auto",
    isAutoGenerated: true,
    source: "speech",
    text: transcript.text,
    segments:
      segments.length > 0
        ? segments
        : [
            {
              start: 0,
              duration: audio.durationSec || 1,
              text: transcript.text,
            },
          ],
  };
}

async function getTranscript(
  url: string,
  language: string,
): Promise<YoutubeTranscriptResult> {
  try {
    const result = await fetchYoutubeTranscript(url, { language });
    return { ...result, source: "captions" };
  } catch (captionErr) {
    const captionMessage =
      captionErr instanceof Error
        ? captionErr.message
        : "Could not extract captions.";
    if (!isNoCaptionsError(captionMessage)) {
      throw captionErr;
    }
    return transcribeFromSpeech(url, language);
  }
}

async function summarizeTranscript(input: {
  title: string;
  transcript: string;
  truncated: boolean;
  style: YoutubeSummaryStyleId;
}): Promise<string> {
  const apiKey = process.env.POLLINATIONS_API_KEY?.trim();
  const systemPrompt = buildYoutubeSummarySystemPrompt(input.style);
  const userPrompt = buildYoutubeSummaryUserPrompt({
    title: input.title,
    transcript: input.transcript,
    truncated: input.truncated,
  });

  const chatBody = {
    model: "openai",
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ],
    temperature: 0.35,
  };

  const headers: Record<string, string> = {
    Accept: "application/json, text/plain;q=0.9,*/*;q=0.8",
    "Content-Type": "application/json",
  };
  if (apiKey) {
    headers.Authorization = `Bearer ${apiKey}`;
  }

  let upstream: Response;
  try {
    upstream = await fetch("https://text.pollinations.ai/openai", {
      method: "POST",
      headers,
      body: JSON.stringify(chatBody),
      cache: "no-store",
      signal: AbortSignal.timeout(55_000),
    });
  } catch {
    throw new SummarizeError(
      "The summary service timed out. Wait a moment and try again.",
      504,
    );
  }

  if (!upstream.ok) {
    if (upstream.status === 429) {
      throw new SummarizeError(
        "Too many requests right now. Wait about 15 seconds and try again.",
        429,
      );
    }

    if (upstream.status === 401 || upstream.status === 402) {
      throw new SummarizeError(
        "Summarization is temporarily unavailable. Try again in a minute, or set POLLINATIONS_API_KEY for higher limits.",
        503,
      );
    }

    throw new SummarizeError(
      "Could not summarize this video. Try again in a moment.",
      502,
    );
  }

  const contentType = upstream.headers.get("content-type") ?? "";
  let summary: string | null = null;

  if (contentType.includes("application/json")) {
    const data = (await upstream.json().catch(() => null)) as unknown;
    summary = extractGeneratedText(data);
  } else {
    const text = (await upstream.text()).trim();
    summary = text || null;
  }

  if (!summary) {
    throw new SummarizeError(
      "The summary service returned an empty result. Try again.",
      502,
    );
  }

  return summary
    .replace(/^(here(?:'s| is) (?:a |your )?summary[:\s-]*)/i, "")
    .trim();
}

class SummarizeError extends Error {
  status: number;

  constructor(message: string, status: number) {
    super(message);
    this.name = "SummarizeError";
    this.status = status;
  }
}

export async function POST(request: Request) {
  let body: RequestBody;
  try {
    body = (await request.json()) as RequestBody;
  } catch {
    return jsonError("Invalid JSON body.", 400);
  }

  const url = typeof body.url === "string" ? body.url : "";
  const urlError = validateYoutubeUrl(url);
  if (urlError) return jsonError(urlError, 400);

  if (!isYoutubeSummaryStyleId(body.style)) {
    return jsonError("Choose a valid summary style.", 400);
  }
  const style = body.style;

  const language =
    typeof body.language === "string" && body.language.trim()
      ? body.language.trim()
      : "auto";

  try {
    const transcriptResult = await getTranscript(url, language);
    const plain = formatTranscriptOutput(transcriptResult, "plain");
    if (!plain.trim()) {
      return jsonError("Could not extract text from this YouTube video.", 422);
    }

    const { text: transcript, truncated } = truncateTranscriptForSummary(plain);
    const summary = await summarizeTranscript({
      title: transcriptResult.title,
      transcript,
      truncated,
      style,
    });

    if (!summary) {
      return jsonError(
        "Could not summarize this video. Try again in a moment.",
        502,
      );
    }

    return Response.json(
      {
        videoId: transcriptResult.videoId,
        title: transcriptResult.title,
        language: transcriptResult.language,
        languageCode: transcriptResult.languageCode,
        isAutoGenerated: transcriptResult.isAutoGenerated,
        source: transcriptResult.source ?? "captions",
        style,
        truncated,
        summary,
      },
      {
        status: 200,
        headers: { "Cache-Control": "no-store" },
      },
    );
  } catch (err) {
    if (err instanceof SummarizeError) {
      return jsonError(err.message, err.status);
    }

    if (err instanceof GroqTranscribeError) {
      return jsonError(err.message, err.status);
    }

    const message =
      err instanceof Error
        ? err.message
        : "Could not summarize this YouTube video.";

    const status =
      /valid YouTube|Paste a YouTube|up to \d+ minutes/i.test(message)
        ? 400
        : /No captions|empty|unavailable|restricted|region-locked|No speech/i.test(
              message,
            )
          ? 422
          : /not configured|GROQ_API_KEY/i.test(message)
            ? 503
            : 502;

    return jsonError(message, status);
  }
}
